name: Select Xcode version
description: Select the Xcode version to be used to compile the apps

runs:
  using: "composite"
  steps:
    # Use the default Xcode pre-selected on Github Actions
    # which is expected to always have the corresponding iOS runtime pre-installed.
    - name: Warm up Xcode
      shell: bash
      run: |
        xcode-select -p
        xcodebuild -version
        sudo xcodebuild -runFirstLaunch
        sudo xcodebuild -license accept
