name: Update Swift Packages and commit the changes

on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: job-update-packages
  cancel-in-progress: false

jobs:
  build:
    runs-on: macos-15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Select Xcode version
      uses: ./.github/actions/select-xcode-version

    # Remove the Package.resolved file and don't use any cached packages to cause all packages to update
    - name: Update packages
      run: |
        rm Cobrowse.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
        xcodebuild -resolvePackageDependencies -clonedSourcePackagesDirPath ./packages

    # If SDKs were updated, commit the changes
    - name: Create a new pull request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FILES_TO_COMMIT: Cobrowse.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
      run: |
        if [[ `git status --porcelain $FILES_TO_COMMIT` ]]; then
          # Commit as Github Actions Bot
          # https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add $FILES_TO_COMMIT
          git commit -m "feat: update swift packages"
          git push
        else
          echo "No changes to commit"
        fi